kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-gp3
allowVolumeExpansion: true
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  type: gp3