apiVersion: v1
kind: Service
metadata:
  name: {{ include "lighthouse.fullname" . }}-loadbalancer
  labels:
    {{- include "lighthouse.labels" . | nindent 4 }}
  annotations:
    {{- include "lighthouse.annotations" . | nindent 4 }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: p2p-tcp
      port: {{ .Values.lighthouse.p2pPort }}
      targetPort: p2p-tcp
      protocol: TCP
  selector:
    {{- include "lighthouse.labels" . | nindent 4 }}