apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lighthouse.fullname" . }}-disk
  labels:
    {{- include "lighthouse.labels" . | nindent 4 }}
spec:
  {{- if ne .Values.volume.name "" }}
  volumeName: {{ .Values.volume.name }}
  {{- end }}
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.volume.storageClass }}
  resources:
    requests:
      storage: {{ .Values.volume.size }}