deploy:
  cluster: "example"
  nodeLabel: "example"

replicaCount: 1

mev:
  enabled: true
  serviceName: mev-boost

lighthouse:
  network: goerli
  gethServiceName: geth
  jwtSecretName: jwt-secret
  jwtSecretFilename: jwt.hex
  httpPort: 5052
  p2pPort: 9000
  metricsPort: 5054
  checkpointSyncEndpoint: https://mainnet.checkpoint.sigp.io
  
image:
  repository: sigp/lighthouse
  pullPolicy: IfNotPresent
  tag: ""

externalResources:
  resourceGroupName: ""
  loadBalancerIP: 0.0.0.0

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: ""

volume:
  name: ""
  storageClass: "ebs-gp3"
  size: "150Gi"

resources: {}
  # limits:
  #   cpu: 4000m
  #   memory: 16Gi
  # requests:
  #   cpu: 2000m
  #   memory: 8Gi