deploy:
  cluster: "example"
  nodeLabel: "example"

replicaCount: 1

privateMempool:
  enabled: false

geth:
  network: "goerli"
  jwtSecretName: jwt-secret
  jwtSecretFilename: jwt.hex
  httpApiNamespace: db,eth,net,engine,rpc,web3,admin
  httpRpcPort: 8545
  wsRpcPort: 8546
  authRpcPort: 8551
  p2pPort: 30303
  metricsPort: 6060
  nodiscover: false
  maxpeers: 1

image:
  repository: ethereum/client-go
  pullPolicy: IfNotPresent
  tag: ""

externalResources:
  resourceGroupName: ""
  loadBalancerIP: 0.0.0.0

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: ""

volume:
  name: ""
  storageClass: "ebs-gp3"
  size: "300Gi"

resources: {}
  # limits:
  #   cpu: 4000m
  #   memory: 16Gi
  # requests:
  #   cpu: 2000m
  #   memory: 4Gi{{- if ne .Values.volume.name "" }}