#             _   _
#   __ _  ___| |_| |__
#  / _` |/ _ \ __| '_ \
# | (_| |  __/ |_| | | |
#  \__, |\___|\__|_| |_|
#  |___/
geth:
  # Only one of the execution layer subcharts should be enabled
  enabled: true
  
  # Overide the default values
  deploy:
    cluster: "a4x-product-cluster"
    nodeLabel: "private-mempool-ng"
  replicaCount: 1
  volume:
    name: ""
    storageClass: "gp2"
    size: "300Gi"
  resources: {}
  privateMempool:
    enabled: true

  geth:
    network: "goerli"
    jwtSecretName: jwt-secret
    jwtSecretFilename: jwt.hex
    httpApiNamespace: db,eth,net,engine,rpc,web3,admin
    httpRpcPort: 8545
    wsRpcPort: 8546
    authRpcPort: 8551
    p2pPort: 30303
    metricsPort: 6060
    nodiscover: true
    maxpeers: 1

  #  _ _       _     _   _                              _
  # | (_)     | |   | | | |                            | |
  # | |_  __ _| |__ | |_| |__   ___  _   _ ___  ___    | |__  _ __
  # | | |/ _` | '_ \| __| '_ \ / _ \| | | / __|/ _ \   | '_ \| '_ \
  # | | | (_| | | | | |_| | | | (_) | |_| \__ \  __/   | |_) | | | |
  # |_|_|\__, |_| |_|\__|_| |_|\___/ \__,_|___/\___|   |_.__/|_| |_|
  #       __/ |
  #      |___/
lighthouse:
  # Only one of the consensus layer subcharts should be enabled
  enabled: true

  # Overide the default values
  deploy:
    cluster: "a4x-product-cluster"
    nodeLabel: "private-mempool-ng"
  replicaCount: 1
  volume:
    name: ""
    storageClass: "gp2"
    size: "150Gi"
  lighthouse:
    checkpointSyncEndpoint: https://sync-goerli.beaconcha.in
  resources: {}
